context:
  version: "4.3.0"

package:
  name: servestatic
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/s/servestatic/servestatic-${{ version }}.tar.gz
    sha256: 76ccf85cf5acc818348cff3fbcf7343ef182fd90aab6d6a18f038401b609f411

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0.0
    - asgiref
    - brotli

tests:
  - python:
      imports:
        - servestatic
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/Archmonger/ServeStatic/
  summary: Production-grade static file server for Python WSGI & ASGI.
  license: MIT
  license_file: LICENSE.md
  documentation: https://archmonger.github.io/ServeStatic/

extra:
  recipe-maintainers:
    - carlodri
