context:
  version: "4.2.0"

package:
  name: servestatic
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/s/servestatic/servestatic-${{ version }}.tar.gz
    sha256: b1188412188b5ca9f6f086962c081f27a52d2cc5cfec6453045b6060cc37f8b1

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0.0
    - asgiref
    - brotli

tests:
  - python:
      imports:
        - servestatic
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/Archmonger/ServeStatic/
  summary: Production-grade static file server for Python WSGI & ASGI.
  license: MIT
  license_file: LICENSE.md
  documentation: https://archmonger.github.io/ServeStatic/

extra:
  recipe-maintainers:
    - carlodri
